### ISSUE TITLE
Move "website/" folder to another repository

### ISSUE THREAD

**Issue by er5678ihgfrt5y6ftgtyr** [garlik/4store#144] opened 2017-03-22 13:47 UTC
It's 230MB

**Comment by berezovskyi** [comment] 2017-03-26 15:44
I just created https://github.com/4store/4store.github.io (https://4store.github.io/). This should allow to fix #137.

**Comment by berezovskyi** [comment] 2017-03-26 16:08
And I think this should be closed as a duplicate of #137 actually.

**Comment by swh** [comment] 2017-03-27 07:12
I think you're more onto of this than me, feel free to close anything you think is stale

**Closed by swh** 2017-03-27 07:12 UTC

**Comment by berezovskyi** [comment] 2017-03-27 15:15
Thank you! I can't manage issues without being a collaborator on the project. I promise not to mess up the git repository if you will grant me permissions :)

![bildschirmfoto 2017-03-27 um 17 13 20](https://cloud.githubusercontent.com/assets/64734/24363693/e1cdea18-1310-11e7-9ce8-436016b2690c.png)

**Comment by swh** [comment] 2017-03-27 17:15
Ah, I thought you'd already given yourself permissions!

I'll fix now

**Comment by swh** [comment] 2017-03-28 08:45
I think I've give you write access, but not totally sure.

Happy to add you as a collaborator or whatever the status is, but can't find the settings screen above.
